import { useEffect, useMemo, useState } from "react";
import { useRoute } from "wouter";
import { CalendarRange } from "lucide-react";

type Phase = { id: number; name: string; startDate: string; endDate: string; progress: number; color: string };
type Milestone = { id: number; name: string; dueDate: string; status: string };
export default function ProjectTimeline() {
  const [, params] = useRoute("/projects/:id/timeline"); const projectId = params?.id; const [data, setData] = useState<{ phases: Phase[]; milestones: Milestone[] }>({ phases: [], milestones: [] });
  useEffect(() => { if (projectId) fetch(`/api/projects/${projectId}/timeline`, { credentials: "include" }).then((r) => r.json()).then(setData).catch(() => undefined); }, [projectId]);
  const bounds = useMemo(() => { const dates = [...data.phases.map((p) => p.startDate), ...data.phases.map((p) => p.endDate), ...data.milestones.map((m) => m.dueDate)].sort(); return { start: dates[0] ?? new Date().toISOString().slice(0, 10), end: dates.at(-1) ?? new Date().toISOString().slice(0, 10) }; }, [data]);
  const span = Math.max(1, new Date(bounds.end).getTime() - new Date(bounds.start).getTime()); const position = (date: string) => Math.max(0, Math.min(100, ((new Date(date).getTime() - new Date(bounds.start).getTime()) / span) * 100));
  return <div className="space-y-6"><div><div className="flex items-center gap-3"><CalendarRange className="text-primary" /><h1 className="text-3xl font-bold">Project Timeline</h1></div><p className="text-muted-foreground">Gantt view for project phases and milestones.</p></div><div className="rounded-xl border bg-card p-6 shadow-sm"><div className="mb-5 flex justify-between text-xs text-muted-foreground"><span>{bounds.start}</span><span>{bounds.end}</span></div><div className="space-y-5">{data.phases.map((phase) => <div key={phase.id} className="grid grid-cols-[180px_1fr] items-center gap-4"><div><div className="font-medium">{phase.name}</div><div className="text-xs text-muted-foreground">{phase.progress}% complete</div></div><div className="relative h-8 rounded bg-muted"><div className="absolute h-8 rounded" style={{ left: `${position(phase.startDate)}%`, width: `${Math.max(4, position(phase.endDate) - position(phase.startDate))}%`, backgroundColor: phase.color }}><span className="px-2 text-xs leading-8 text-white">{phase.progress}%</span></div></div></div>)}{data.milestones.map((milestone) => <div key={milestone.id} className="grid grid-cols-[180px_1fr] items-center gap-4"><div className="font-medium">{milestone.name}<div className="text-xs text-muted-foreground">{milestone.dueDate}</div></div><div className="relative h-6 bg-muted"><span className="absolute top-0 h-6 w-1 rounded bg-amber-500" style={{ left: `${position(milestone.dueDate)}%` }} title={milestone.status} /></div></div>)}</div>{!data.phases.length && !data.milestones.length && <div className="py-16 text-center text-muted-foreground">No phases or milestones have been defined for this project.</div>}</div></div>;
}
