ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "clerk_user_id" text;
CREATE UNIQUE INDEX IF NOT EXISTS "users_clerk_user_id_unique" ON "users" ("clerk_user_id");
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "organization_id" integer NOT NULL DEFAULT 1;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "storage_path" text;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'documents_organization_id_organizations_id_fk') THEN
    ALTER TABLE "documents" ADD CONSTRAINT "documents_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id");
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS "permissions" ("id" serial PRIMARY KEY, "key" text NOT NULL UNIQUE, "description" text);
CREATE TABLE IF NOT EXISTS "roles" ("id" serial PRIMARY KEY, "name" text NOT NULL, "organization_id" integer NOT NULL REFERENCES "organizations"("id"));
CREATE TABLE IF NOT EXISTS "role_permissions" ("role_id" integer NOT NULL REFERENCES "roles"("id") ON DELETE CASCADE, "permission_id" integer NOT NULL REFERENCES "permissions"("id") ON DELETE CASCADE, PRIMARY KEY ("role_id", "permission_id"));
CREATE TABLE IF NOT EXISTS "user_roles" ("user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE, "role_id" integer NOT NULL REFERENCES "roles"("id") ON DELETE CASCADE, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("user_id", "role_id"));
CREATE TABLE IF NOT EXISTS "project_phases" ("id" serial PRIMARY KEY, "project_id" integer NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE, "organization_id" integer NOT NULL REFERENCES "organizations"("id"), "name" text NOT NULL, "description" text, "start_date" date NOT NULL, "end_date" date NOT NULL, "progress" integer NOT NULL DEFAULT 0, "color" text NOT NULL DEFAULT '#2563eb', "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "milestones" ("id" serial PRIMARY KEY, "project_id" integer NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE, "organization_id" integer NOT NULL REFERENCES "organizations"("id"), "phase_id" integer REFERENCES "project_phases"("id") ON DELETE SET NULL, "name" text NOT NULL, "due_date" date NOT NULL, "status" text NOT NULL DEFAULT 'pending', "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "workflows" ("id" serial PRIMARY KEY, "organization_id" integer NOT NULL REFERENCES "organizations"("id"), "name" text NOT NULL, "entity_type" text NOT NULL, "active" integer NOT NULL DEFAULT 1, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "workflow_steps" ("id" serial PRIMARY KEY, "workflow_id" integer NOT NULL REFERENCES "workflows"("id") ON DELETE CASCADE, "step_order" integer NOT NULL, "name" text NOT NULL, "required_permission" text NOT NULL, "status" text NOT NULL DEFAULT 'pending');
CREATE TABLE IF NOT EXISTS "workflow_runs" ("id" serial PRIMARY KEY, "workflow_id" integer NOT NULL REFERENCES "workflows"("id"), "organization_id" integer NOT NULL REFERENCES "organizations"("id"), "entity_type" text NOT NULL, "entity_id" integer NOT NULL, "current_step" integer NOT NULL DEFAULT 1, "status" text NOT NULL DEFAULT 'pending', "submitted_by" integer REFERENCES "users"("id"), "payload" jsonb, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
INSERT INTO permissions (key, description) VALUES
('projects.read','View projects'),('projects.create','Create projects'),('projects.update','Update projects'),('projects.delete','Delete projects'),('tasks.read','View tasks'),('tasks.create','Create tasks'),('tasks.update','Update tasks'),('tasks.delete','Delete tasks'),('cost-control.read','View cost control'),('cost-control.manage','Manage cost control'),('documents.read','View documents'),('documents.create','Upload documents'),('documents.delete','Delete documents'),('planning.read','View planning'),('planning.manage','Manage planning'),('workflows.read','View workflows'),('workflows.manage','Define workflows'),('workflows.execute','Start workflows'),('workflows.approve','Approve workflow steps'),('ai.use','Use AI assistant') ON CONFLICT (key) DO NOTHING;
INSERT INTO roles (name, organization_id) SELECT r.name, o.id FROM organizations o CROSS JOIN (VALUES ('CEO'),('ProjectDirector'),('ProjectManager'),('PlanningEngineer'),('SiteEngineer'),('Supervisor'),('HR'),('Accountant'),('WarehouseManager'),('ProcurementOfficer'),('Worker')) r(name) WHERE NOT EXISTS (SELECT 1 FROM roles x WHERE x.name=r.name AND x.organization_id=o.id);
INSERT INTO user_roles (user_id, role_id) SELECT u.id, r.id FROM users u JOIN roles r ON r.organization_id=u.organization_id AND r.name=u.role WHERE NOT EXISTS (SELECT 1 FROM user_roles ur WHERE ur.user_id=u.id AND ur.role_id=r.id);
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r CROSS JOIN permissions p WHERE r.name IN ('CEO','ProjectDirector') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.key IN ('projects.read','projects.create','projects.update','tasks.read','tasks.create','tasks.update','planning.read','planning.manage','documents.read','documents.create','cost-control.read','workflows.read','workflows.execute','ai.use') WHERE r.name IN ('ProjectManager','PlanningEngineer','SiteEngineer','Supervisor') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.key IN ('cost-control.read','cost-control.manage','workflows.read','workflows.approve','ai.use') WHERE r.name='Accountant' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r JOIN permissions p ON p.key IN ('documents.read','documents.create','tasks.read','tasks.update','ai.use') WHERE r.name IN ('HR','WarehouseManager','ProcurementOfficer','Worker') ON CONFLICT DO NOTHING;
