import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import documentsRouter from "./documents";
import contractsRouter from "./contracts";
import dailyReportsRouter from "./daily-reports";
import meetingsRouter from "./meetings";
import usersRouter from "./users";
import equipmentRouter from "./equipment";
import inventoryRouter from "./inventory";
import procurementRouter from "./procurement";
import notificationsRouter from "./notifications";
import organizationsRouter from "./organizations";
import costControlRouter from "./cost-control";
import crmRouter from "./crm";
import searchRouter from "./search";
import phase2Router from "./phase2";
import planningRouter from "./planning";
import workflowsRouter from "./workflows";
import formsRouter from "./forms";
import aiRouter from "./ai";
import qualityRouter from "./quality";
import { attachTenant } from "../middlewares/tenant";
import contractsBoqRouter from "./contracts-boq";
import hrRouter from "./hr";
import procurementExtRouter from "./procurement-ext";

const router: IRouter = Router();

router.use(healthRouter);
router.use(attachTenant);
router.use(dashboardRouter);
router.use(projectsRouter);
router.use(tasksRouter);
router.use(documentsRouter);
router.use(contractsRouter);
router.use(dailyReportsRouter);
router.use(meetingsRouter);
router.use(usersRouter);
router.use(equipmentRouter);
router.use(inventoryRouter);
router.use(procurementRouter);
router.use(notificationsRouter);
router.use(organizationsRouter);
router.use(costControlRouter);
router.use(crmRouter);
router.use(searchRouter);
router.use(phase2Router);
router.use(planningRouter);
router.use(workflowsRouter);
router.use(formsRouter);
router.use(aiRouter);
router.use(qualityRouter);
router.use(contractsBoqRouter);
router.use(hrRouter);
router.use(procurementExtRouter);

export default router;
