import { Router } from "express";
import { and, asc, eq } from "drizzle-orm";
import { db, workflowsTable, workflowStepsTable, workflowRunsTable } from "@workspace/db";
import { requirePermission } from "../middlewares/permissions";
import { tenantId } from "../middlewares/tenant";

const router = Router();
router.get("/workflows", requirePermission("workflows.read"), async (req, res) => { const workflows = await db.select().from(workflowsTable).where(eq(workflowsTable.organizationId, tenantId(req))); res.json(workflows); });
router.post("/workflows", requirePermission("workflows.manage"), async (req, res): Promise<void> => { const { name, entityType, steps } = req.body ?? {}; if (!name || !entityType || !Array.isArray(steps) || !steps.length) { res.status(400).json({ error: "name, entityType and steps are required" }); return; } const [workflow] = await db.insert(workflowsTable).values({ name, entityType, organizationId: tenantId(req) }).returning(); await db.insert(workflowStepsTable).values(steps.map((step: any, index: number) => ({ workflowId: workflow.id, stepOrder: index + 1, name: step.name, requiredPermission: step.requiredPermission }))); res.status(201).json({ ...workflow, steps: await db.select().from(workflowStepsTable).where(eq(workflowStepsTable.workflowId, workflow.id)).orderBy(asc(workflowStepsTable.stepOrder)) }); });
router.post("/workflows/:id/runs", requirePermission("workflows.execute"), async (req, res): Promise<void> => { const [workflow] = await db.select().from(workflowsTable).where(and(eq(workflowsTable.id, Number(req.params.id)), eq(workflowsTable.organizationId, tenantId(req)))); if (!workflow) { res.status(404).json({ error: "Workflow not found" }); return; } const [run] = await db.insert(workflowRunsTable).values({ workflowId: workflow.id, organizationId: tenantId(req), entityType: workflow.entityType, entityId: Number(req.body.entityId), submittedBy: req.vetraUser?.id, payload: req.body.payload ?? {} }).returning(); res.status(201).json(run); });
router.post("/workflow-runs/:id/decision", requirePermission("workflows.approve"), async (req, res): Promise<void> => { const [run] = await db.select().from(workflowRunsTable).where(and(eq(workflowRunsTable.id, Number(req.params.id)), eq(workflowRunsTable.organizationId, tenantId(req)))); if (!run) { res.status(404).json({ error: "Workflow run not found" }); return; } const decision = req.body.decision; if (!["approve", "reject"].includes(decision)) { res.status(400).json({ error: "decision must be approve or reject" }); return; } const [step] = await db.select().from(workflowStepsTable).where(and(eq(workflowStepsTable.workflowId, run.workflowId), eq(workflowStepsTable.stepOrder, run.currentStep))); if (!step) { res.status(409).json({ error: "Workflow has no current step" }); return; } const nextStatus = decision === "reject" ? "rejected" : "pending"; const nextStep = decision === "approve" ? run.currentStep + 1 : run.currentStep; const allSteps = await db.select().from(workflowStepsTable).where(eq(workflowStepsTable.workflowId, run.workflowId)); const status = decision === "reject" ? "rejected" : nextStep > allSteps.length ? "approved" : nextStatus; const [updated] = await db.update(workflowRunsTable).set({ currentStep: nextStep, status, updatedAt: new Date() }).where(eq(workflowRunsTable.id, run.id)).returning(); res.json(updated); });
export default router;
