import { t } from '@/lib/i18n';
import { useState } from "react";
import { Bot, Send, User } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Message = { role: "user" | "assistant"; text: string };
export default function AIAssistant() {
  const [query, setQuery] = useState(""); const [busy, setBusy] = useState(false); const [messages, setMessages] = useState<Message[]>([{ role: "assistant", text: t('ai.greeting') }]);
  const send = async (event: React.FormEvent) => { event.preventDefault(); const text = query.trim(); if (!text || busy) return; setQuery(""); setMessages((current) => [...current, { role: "user", text }]); setBusy(true); try { const response = await fetch("/api/ai/assistant", { method: "POST", headers: { "content-type": "application/json" }, credentials: "include", body: JSON.stringify({ query: text }) }); const data = await response.json(); setMessages((current) => [...current, { role: "assistant", text: data.answer ?? data.error ?? t('ai.assistant') }]); } catch { setMessages((current) => [...current, { role: "assistant", text: t('ai.assistant') }]); } finally { setBusy(false); } };
  return <div className="mx-auto flex max-w-4xl flex-col gap-6"><div><div className="flex items-center gap-3"><Bot className="text-primary" /><h1 className="text-3xl font-bold">{t('ai.title')}</h1></div><p className="text-muted-foreground">{t('ai.desc')}</p></div><div className="flex min-h-[520px] flex-col rounded-xl border bg-card shadow-sm"><div className="flex-1 space-y-4 overflow-y-auto p-6">{messages.map((message, index) => <div key={index} className={`flex gap-3 ${message.role === "user" ? "justify-end" : "justify-start"}`}><div className={`flex max-w-[80%] gap-3 rounded-lg px-4 py-3 ${message.role === "user" ? "bg-primary text-primary-foreground" : "bg-muted"}`}>{message.role === "assistant" ? <Bot className="mt-1 h-4 w-4 shrink-0" /> : <User className="mt-1 h-4 w-4 shrink-0" />}<p className="whitespace-pre-wrap text-sm">{message.text}</p></div></div>)}{busy && <div className="text-sm text-muted-foreground">{t('ai.thinking')}</div>}</div><form onSubmit={send} className="flex gap-3 border-t p-4"><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={t('ai.askPlaceholder')} aria-label={t('ai.queryLabel')} /><Button type="submit" disabled={busy || !query.trim()}><Send className="mr-2 h-4 w-4" />{t('ai.send')}</Button></form></div></div>;
}
