import { useRef, useState } from "react";
import { useListDocuments } from "@workspace/api-client-react";
import { Plus, Search, Filter, FileText, Download, MoreHorizontal, File, Image as ImageIcon, FileSpreadsheet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Link } from "wouter";
import { formatJalali } from "@/lib/jalali";

export default function DocumentList() {
  const [search, setSearch] = useState(""); const [projectId, setProjectId] = useState(""); const [uploading, setUploading] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const { data: documents, isLoading, refetch } = useListDocuments();
  const getFileIcon = (type: string) => type.includes("pdf") ? <FileText className="h-5 w-5 text-red-500" /> : type.includes("image") ? <ImageIcon className="h-5 w-5 text-blue-500" /> : type.includes("spreadsheet") || type.includes("excel") ? <FileSpreadsheet className="h-5 w-5 text-emerald-500" /> : <File className="h-5 w-5 text-muted-foreground" />;
  const formatSize = (bytes: number) => bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1048576).toFixed(1)} MB`;
  const upload = async (file?: File) => { if (!file || !projectId) { window.alert("Enter a project ID before uploading."); return; } setUploading(true); try { const form = new FormData(); form.append("file", file); form.append("projectId", projectId); const response = await fetch("/api/documents/upload", { method: "POST", body: form, credentials: "include" }); if (!response.ok) throw new Error(await response.text()); await refetch(); } catch (error) { window.alert(error instanceof Error ? error.message : "Upload failed"); } finally { setUploading(false); } };
  const visibleDocs = documents?.filter((doc) => doc.name.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-6"><div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Documents</h1><p className="text-muted-foreground">Manage blueprints, contracts, and project files.</p></div><div className="flex gap-2"><Input className="w-28" placeholder="Project ID" value={projectId} onChange={(e) => setProjectId(e.target.value)} /><input ref={inputRef} type="file" className="hidden" onChange={(e) => upload(e.target.files?.[0])} /><Button className="shrink-0 gap-2" disabled={uploading} onClick={() => inputRef.current?.click()}><Plus className="h-4 w-4" /> {uploading ? "Uploading..." : "Upload Document"}</Button></div></div><div className="flex flex-col sm:flex-row gap-4 justify-between items-center bg-card p-4 rounded-lg border shadow-sm"><div className="relative w-full sm:w-96"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><Input placeholder="Search documents..." className="pl-9 font-sans" value={search} onChange={(e) => setSearch(e.target.value)} /></div><Button variant="outline" className="gap-2"><Filter className="h-4 w-4" /> Filter Type</Button></div><div className="bg-card border rounded-lg shadow-sm overflow-hidden">{isLoading ? <div className="py-20 text-center font-mono text-muted-foreground">LOADING DOCUMENTS...</div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-muted/50 text-left text-muted-foreground"><th className="py-3 px-4 w-10"></th><th className="py-3 px-4">Name</th><th className="py-3 px-4">Project</th><th className="py-3 px-4">Uploaded By</th><th className="py-3 px-4">Size</th><th className="py-3 px-4">Date</th><th className="py-3 px-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{visibleDocs?.map((doc) => <tr key={doc.id} className="group hover:bg-muted/50"><td className="py-3 px-4">{getFileIcon(doc.type)}</td><td className="py-3 px-4 font-medium">{doc.name}</td><td className="py-3 px-4"><Link href={`/projects/${doc.projectId}`} className="text-primary hover:underline text-xs">{doc.projectName}</Link></td><td className="py-3 px-4 text-muted-foreground text-xs">{doc.uploadedBy}</td><td className="py-3 px-4 text-muted-foreground font-mono text-xs">{formatSize(doc.size)}</td><td className="py-3 px-4 text-muted-foreground font-mono text-xs">{formatJalali(doc.createdAt)}</td><td className="py-3 px-4 text-right"><div className="flex items-center justify-end gap-2"><a href={doc.url ?? "#"} target="_blank" rel="noreferrer"><Button variant="ghost" size="icon" className="h-8 w-8"><Download className="h-4 w-4" /></Button></a><Button variant="ghost" size="icon" className="h-8 w-8"><MoreHorizontal className="h-4 w-4" /></Button></div></td></tr>)}</tbody></table></div>}</div></div>;
}
